// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4NIhPd819inVnPkD-OrnrUurmFYHspE',
    appId: '1:925602616896:web:1160d0d804b0ba47f671a5',
    messagingSenderId: '925602616896',
    projectId: 'auth-app-9669f',
    authDomain: 'auth-app-9669f.firebaseapp.com',
    storageBucket: 'auth-app-9669f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2OyLEm8YH2yzZy8Mmu3OIQ0G7hUb9rXo',
    appId: '1:925602616896:android:f7929a394dc5e281f671a5',
    messagingSenderId: '925602616896',
    projectId: 'auth-app-9669f',
    storageBucket: 'auth-app-9669f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoe9ssYKHwV91s8jtufrNTW5ZZsWzOyWI',
    appId: '1:925602616896:ios:97f6e7d6aff7b638f671a5',
    messagingSenderId: '925602616896',
    projectId: 'auth-app-9669f',
    storageBucket: 'auth-app-9669f.appspot.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoe9ssYKHwV91s8jtufrNTW5ZZsWzOyWI',
    appId: '1:925602616896:ios:97f6e7d6aff7b638f671a5',
    messagingSenderId: '925602616896',
    projectId: 'auth-app-9669f',
    storageBucket: 'auth-app-9669f.appspot.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4NIhPd819inVnPkD-OrnrUurmFYHspE',
    appId: '1:925602616896:web:5d601016e2a6d0a0f671a5',
    messagingSenderId: '925602616896',
    projectId: 'auth-app-9669f',
    authDomain: 'auth-app-9669f.firebaseapp.com',
    storageBucket: 'auth-app-9669f.appspot.com',
  );
}
